-- USER 테이블
-- U_ID : 아이디 / U_BIRTH : 생년월일 / U_GENDER : 성별 /
-- P_NUM : USER 전화번호 /  U_NATION : 국적
CREATE TABLE V_USER(
	U_ID VARCHAR2(20) PRIMARY KEY,
	U_BIRTH CHAR(6) NOT NULL,
	U_GENDER CHAR(2) CHECK (U_GENDER IN('F','M')),
	P_NUM VARCHAR(13) NOT NULL,
	U_NATION CHAR(2) CHECK (U_NATION IN('L','F'))
);


-- CONDITION 테이블
-- U_ID : 아이디 / S_NUM : 연번 / VACCINE : 백신종류 / 
-- INOC_F : 1차 접종 / INOC_S : 2차 접종 / INOC_DATE : 접종 날짜
CREATE TABLE V_CONDITION(
	U_ID VARCHAR2(20),
	S_NUM NUMBER(3),
	VACCINE VARCHAR2(10) CHECK (VACCINE IN('화이자', '모더나')),
	INOC_F CHAR(2) CHECK (INOC_F IN ('O', 'X')),
	INOC_S CHAR(2) CHECK (INOC_S IN ('O', 'X')),
	INOC_DATE DATE
);

-- RESERVATION 테이블
-- U_ID : 아이디 / S_NUM : 연번 / VACCINE : 백신종류 / 
-- INOC_DATE : 접종 날짜 / U_NATION : 국적
CREATE TABLE V_RESERVATION(
	U_ID VARCHAR2(20),
	S_NUM NUMBER(3),
	VACCINE VARCHAR2(10) CHECK (VACCINE IN ('화이자', '모더나')),
	INOC_DATE DATE,
	U_NATION CHAR(2) CHECK (U_NATION IN('L','F'))
);

-- V_CONDITION INOC_F, INOC_S 기본값 설정
ALTER TABLE V_CONDITION MODIFY (INOC_F DEFAULT 'X');
ALTER TABLE V_CONDITION MODIFY (INOC_S DEFAULT 'X');

-- V_CENTER S_NUM PK 설정
ALTER TABLE V_CENTER ADD CONSTRAINT S_NUM_PK PRIMARY KEY (S_NUM);

-- V_CONDITION U_ID FK 설정
ALTER TABLE V_CONDITION ADD CONSTRAINT U_ID_FK 
FOREIGN KEY (U_ID) REFERENCES V_USER(U_ID);

-- V_CONDITION S_NUM FK 설정
ALTER TABLE V_CONDITION ADD CONSTRAINT S_NUM_FK 
FOREIGN KEY (S_NUM) REFERENCES V_CENTER(S_NUM);

-- V_RESERVATION U_ID FK 설정
ALTER TABLE V_RESERVATION ADD CONSTRAINT C_U_ID_FK 
FOREIGN KEY (U_ID) REFERENCES V_USER(U_ID);

-- V_RESERVATION S_NUM FK 설정
ALTER TABLE V_RESERVATION ADD CONSTRAINT C_S_NUM_FK 
FOREIGN KEY (S_NUM) REFERENCES V_CENTER(S_NUM);


SELECT * FROM V_USER;
SELECT * FROM V_CONDITION;
SELECT * FROM V_RESERVATION;
SELECT * FROM V_CENTER;
